default:
  @just --list

build-html-from-mediawiki:
  pandoc -f mediawiki --syntax-highlighting "pygments" -o "Prolog&Elixir.html" "Prolog&Elixir.wiki" #--syntax-highlighting breezedark theme not working on windows
